name: flutter_demo_app
description: "A new Flutter project."
publish_to: "none"

version: 1.4.5-dev

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

workspace:
  - packages/core
  - packages/dependency
  - packages/design_system
  - packages/clean_code_data
  - packages/clean_code_domain
  - packages/clean_code_infra
  - packages/appsflyer
  - packages/firebase_initialize
  - packages/analytics
  - packages/app_purchase
  - packages/crashlytics
  - packages/deeplink
  - packages/feature_flag
  - packages/notifications
  - packages/push_notifications
  - packages/push_messaging
  - packages/splash
  - packages/onboarding
  - packages/force_update
  - packages/security
  - packages/login
  - packages/admin
  - packages/home
  - packages/settings
  - packages/faq
  - packages/user_account
  - packages/web_app
  - packages/webview

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  core:
    path: packages/core
  dependency:
    path: packages/dependency
  design_system:
    path: packages/design_system

  clean_code_data:
    path: packages/clean_code_data
  clean_code_domain:
    path: packages/clean_code_domain
  clean_code_infra:
    path: packages/clean_code_infra

  # appsflyer:
  #   path: packages/appsflyer
  # firebase_initialize:
  #   path: packages/firebase_initialize
  app_purchase:
    path: packages/app_purchase
  analytics:
    path: packages/analytics
  crashlytics:
    path: packages/crashlytics
  deeplink:
    path: packages/deeplink
  feature_flag:
    path: packages/feature_flag
  notifications:
    path: packages/notifications
  # push_notifications:
  #   path: packages/push_notifications
  # push_messaging:
  #   path: packages/push_messaging

  splash:
    path: packages/splash
  onboarding:
    path: packages/onboarding
  force_update:
    path: packages/force_update
  security:
    path: packages/security
  login:
    path: packages/login
  admin:
    path: packages/admin
  home:
    path: packages/home
  settings:
    path: packages/settings
  user_account:
    path: packages/user_account
  web_app:
    path: packages/web_app
  webview:
    path: packages/webview

dependency_overrides:
  device_info_plus: 12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: 6.0.0
  very_good_analysis: 10.2.0
  flutter_launcher_icons: 0.14.4 # flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons*
  package_rename: 1.10.1
  faker: 2.2.0
  mocktail: 1.0.5
  build_runner: 2.15.0 # dart run build_runner build
  bdd_widget_test: 2.1.4

flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: false

  assets:
    - assets/fonts/
    - assets/html/
    - assets/jpeg/
    - assets/png/
    - assets/svg/
    - assets/json/

  fonts:
    - family: Montserrat Black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: Montserrat Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat Thin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf

# dart run flutter_native_splash:create
flutter_native_splash:
  android: false
  ios: false
  web: false
  fullscreen: false
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  color: "#FF5722"
  image: "assets/png/AppIcon.png"
  android_12:
    color: "#FF5722"
    icon_background_color: "#FF5722"
    icon_background_color_dark: "#FF5722"

# dart run package_rename
package_rename_config:
  macos:
    copyright_notice: Copyright ©️ 2026 Fortress. All rights reserved.
  web:
    app_name: Fortress
    short_app_name: Fortress
    description: Password Manager
