name: flutter_demo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  get: ^4.6.6
  dio: ^5.6.0
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  # flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 # flutter pub run flutter_launcher_icons
  flutter_native_splash: ^2.4.1 # dart run flutter_native_splash:create

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/png/
    - assets/svg/
  
  fonts:
    - family: Montserrat Black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: Montserrat Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat Thin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
      
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/png/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/png/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/png/logo.png"

flutter_native_splash:
  android: true
  ios: false
  color: "#ffffff"
  image: assets/png/logo.png
  branding: assets/png/branding.png
  android_12:
    color: "#ffffff"