name: dependency
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.10.1
  flutter: ">=3.38.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Localizations
  intl: 0.20.2

  # Dependecy Injection
  get: 4.7.3
  get_it: 9.2.1

  # Http
  dio: 5.9.0
  cached_network_image: 3.4.1

  # Logger
  talker: 5.1.9

  # Local Storage
  shared_preferences: 2.5.4
  flutter_secure_storage: 10.0.0

  # Storage
  path: 1.9.1
  path_provider: 2.1.5

  # Database
  hive: 2.2.3
  hive_flutter: 1.1.0

  # Fonts
  google_fonts: 6.3.3

  # Icons
  cupertino_icons: 1.0.8
  icons_plus: 5.0.0

  # SVG
  flutter_svg: 2.2.3

  # Firebase
  # firebase_core: 4.2.1

  # Analytics
  aptabase_flutter: 0.4.1
  # firebase_analytics: 12.0.4

  # Crashlytics
  sentry_flutter: 9.9.1
  sentry_dio: 9.9.1

  # Deeplink
  app_links: 6.4.1

  # Feature Flag
  flagsmith: 6.1.0
  growthbook_sdk_flutter: 4.1.1

  # Push Messaging Notifications
  # firebase_messaging: 16.0.4

  # Permissions
  permission_handler: 12.0.1
  location: 8.0.1

  # Camera
  camerawesome: 2.5.0
  mobile_scanner: 7.1.4

  # Security Encrypt
  crypto: 3.0.7
  # encrypt: 5.0.3
  local_auth: 3.0.0

  # Device Info
  android_id: 0.5.1
  flutter_app_info: 3.0.3

  # Purchase
  in_app_purchase: 3.2.3

  # Utilities
  share_plus: 12.0.1
  dart_either: 2.0.0
  validatorless: 1.2.5
  flutter_native_splash: 2.4.7
  url_launcher: 6.3.2
  flutter_contacts: 1.1.9+2
  internet_connection_checker_plus: 2.9.1+2
  synchronized: 3.4.0
  flutter_dynamic_launcher_icon: 0.0.2
  in_app_review: 2.0.11
  string_normalizer: 0.4.0
  app_settings: 7.0.0

  # Widget
  otp: 3.2.0
  pinput: 6.0.1
  skeletonizer: 2.1.2
  local_captcha: 1.0.5
  introduction_screen: 4.0.0
  flutter_inappwebview: 6.1.5
  intl_phone_field: 3.2.0
  flutter_masked_text3: 0.9.4

  # Dev Dependencies
  faker: 2.2.0
  mocktail: 1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
