name: dependency
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Localizations
  intl: 0.20.2

  # Dependecy Injection
  get: 4.7.3
  get_it: 9.2.1

  # Http
  dio: 5.9.2
  cached_network_image: 3.4.1

  # Logger
  talker: 5.1.17

  # Local Storage
  shared_preferences: 2.5.5
  flutter_secure_storage: 10.3.1

  # Storage
  path: 1.9.1
  path_provider: 2.1.5

  # Database
  hive: 2.2.3
  hive_flutter: 1.1.0

  # Fonts
  # google_fonts: 8.1.0

  # Icons
  cupertino_icons: 1.0.9

  # SVG
  flutter_svg: 2.3.0

  # Analytics
  aptabase_flutter: 0.4.1

  # Crashlytics
  sentry_flutter: 9.21.0 # must update pod install
  sentry_dio: 9.21.0 # must update pod install

  # Deeplink
  app_links: 7.1.1

  # Feature Flag
  flagsmith: 6.1.0

  # Permissions
  permission_handler: 12.0.3
  location: 8.0.1

  # Camera
  camerawesome: 2.5.0
  mobile_scanner: 7.2.0

  # Security Encrypt
  crypto: 3.0.7
  pointycastle: 3.6.2 # 4.0.0
  local_auth: 3.0.1

  # Device Info
  android_id: 0.5.1
  flutter_app_info: 3.0.3

  # Purchase
  in_app_purchase: 3.2.3

  # Utilities
  share_plus: 12.0.2
  # dart_either: 2.0.0
  validatorless: 1.2.5
  flutter_native_splash: 2.4.8
  url_launcher: 6.3.2
  internet_connection_checker_plus: 3.0.1
  synchronized: 3.4.1
  flutter_dynamic_launcher_icon: 0.0.2
  in_app_review: 2.0.12
  string_normalizer: 0.4.0
  app_settings: 7.0.0

  # Widget
  otp: 3.2.0
  pinput: 6.0.2
  skeletonizer: 2.1.3
  local_captcha: 1.0.5
  introduction_screen: 4.0.0
  flutter_inappwebview: 6.1.5
  intl_phone_field: 3.2.0
  flutter_masked_text3: 0.9.4
  flutter_custom_month_picker: 0.1.3

  # Dev Dependencies
  faker: 2.2.0
  mocktail: 1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
