name: push_messaging
version: 0.0.1
homepage:
publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  dependency:
    path: ../dependency
  design_system:
    path: ../design_system

  clean_code_data:
    path: ../clean_code_data
  clean_code_domain:
    path: ../clean_code_domain

  firebase_initialize:
    path: ../firebase_initialize
  analytics:
    path: ../analytics
  crashlytics:
    path: ../crashlytics
  push_notifications:
    path: ../push_notifications

  firebase_messaging: 16.3.0 # must update pod install

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
