name: push_messaging
version: 0.0.1
homepage:
publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.10.1
  flutter: ">=3.38.3"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  dependency:
    path: ../dependency

  firebase_initialize:
    path: ../firebase_initialize
  analytics:
    path: ../analytics
  crashlytics:
    path: ../crashlytics
  push_notifications:
    path: ../push_notifications

  firebase_messaging: 16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
